### ISSUE TITLE
Plugin not working in HA

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [thomasloven/lovelace-q-card#16]
Has anyone gotten this error? I'm kinda lost. I added the plugin by adding the repo to HACS and then installing like normal and it seems to be working since the js file is imported in resources and when i open it contents in the browser is shows the js script.

HA version: 
![image](https://github.com/thomasloven/lovelace-q-card/assets/45077772/358fb286-1f9b-494f-80f5-34285a85355a)

The error:
![image](https://github.com/thomasloven/lovelace-q-card/assets/45077772/24ef6d55-726e-43e7-963b-520cf1e8fe84)

The resource import:
![image](https://github.com/thomasloven/lovelace-q-card/assets/45077772/3f306b02-80ee-4817-b073-6881a85e44a2)

My card definition:
![image](https://github.com/thomasloven/lovelace-q-card/assets/45077772/07778201-7fc7-4175-b02b-b9bf7742d569)

**Comment by DEADSEC-SECURITY** [comment]
Updated to 2023.6 and still not working. Same error appears

**Comment by emeyedeejay** [comment]
I came here looking to see if this had been abandoned ... looks like it has - which is a major pity!
